basic.forever(function () {
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorA, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorB, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorA, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorB, driver.Rotate.Clockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorB)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorB)
    basic.pause(1000)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorA, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorB, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorA, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorB, driver.Rotate.CounterClockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorB)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorB)
    basic.pause(1000)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorA, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorB, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorA, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorB, driver.Rotate.CounterClockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorB)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorB)
    basic.pause(1000)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorA, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorB, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorA, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorB, driver.Rotate.Clockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorB)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorB)
    basic.pause(1000)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorA, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorB, driver.Rotate.Clockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorB)
    basic.pause(1000)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorA, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorB, driver.Rotate.CounterClockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorB)
    basic.pause(1000)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorB, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorA, driver.Rotate.CounterClockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorB)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorA)
    basic.pause(1000)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorB, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorA, driver.Rotate.Clockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorB)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorA)
    basic.pause(1000)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorA, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorB, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorA, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorB, driver.Rotate.Clockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorB)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorB)
    basic.pause(1000)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorA, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add64, driver.Motor.MotorB, driver.Rotate.CounterClockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorA, driver.Rotate.Clockwise, 100)
    driver.controlMotor(driver.Address.add68, driver.Motor.MotorB, driver.Rotate.CounterClockwise, 100)
    basic.pause(1000)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add64, driver.Pause.Stop, driver.Motor.MotorB)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorA)
    driver.pauseMotor(driver.Address.add68, driver.Pause.Stop, driver.Motor.MotorB)
    basic.pause(1000)
})
