def on_forever():
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_A,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_B,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_A,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    basic.pause(1000)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_A,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_A,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_B,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    basic.pause(1000)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_A,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_B,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_A,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_B,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    basic.pause(1000)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_A,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_A,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    basic.pause(1000)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_A,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    basic.pause(1000)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_A,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_B,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    basic.pause(1000)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_B,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_A,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    basic.pause(1000)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_A,
        driver.Rotate.CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    basic.pause(1000)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_A,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_A,
        driver.Rotate.COUNTER_CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    basic.pause(1000)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_A,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD64,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_A,
        driver.Rotate.CLOCKWISE,
        100)
    driver.control_motor(driver.Address.ADD68,
        driver.Motor.MOTOR_B,
        driver.Rotate.CLOCKWISE,
        100)
    basic.pause(1000)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD64,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_A)
    driver.pause_motor(driver.Address.ADD68,
        driver.Pause.STOP,
        driver.Motor.MOTOR_B)
    basic.pause(1000)
basic.forever(on_forever)
